### ISSUE TITLE
Native module RNShakeEventModule tried to override RNShakeEventModule for module name RNShakeEvent. If this was your intention, set canOverrideExistingModule=true

### ISSUE THREAD

**Issue by joncursi** [jadsonlourenco/react-native-shake-event#14]
Got this issue using this library on Android -> RN `0.48.2`:

![screen shot 2017-09-11 at 4 57 40 pm](https://user-images.githubusercontent.com/4974609/30296488-62087f1a-9712-11e7-8dd6-fd5677ad6702.png)

iOS works fine, it's just Android that's being problematic. Any ideas? @negativetwelve

**Comment by joncursi** [comment]
Ah, this was an issue on my own end. Solved via https://stackoverflow.com/a/42885141/3810402

**Comment by negativetwelve** [comment]
thanks for leaving the link to the solution!

**Comment by sadi304** [comment]
hey can you verify this still works on 0.48.x version? on android
