### ISSUE TITLE
Shake event callback is not executing on production build

### ISSUE THREAD

**Issue by amourya-systango** [jadsonlourenco/react-native-shake-event#17]
For debug mode, shake event callback is executing correctly but when running a release build on a real device the callback is not executing. Do you have any idea if I am doing wrong something?

**Comment by zhuber** [comment]
This is also not working for me on iOS. Can't get it to work in expo or the TestFlight build, using the example code shown on the repo README.

**Comment by djhr** [comment]
I've it working fine on production for both Android and iOS. For Android it's a bit rough to shake be detected, you need to shake it quite hard, but works. My code is pretty much what's on the README.

**Comment by jadsonlourenco** [comment]
I recommend to upgrade ReactNative and others thins. Soon will be released a new version of this module, I recommend to use the latest version too. This new version (5.0.0) I have sure that are working fine on debug and production.

Thank you.
