### ISSUE TITLE
Shake event, onBegin

### ISSUE THREAD

**Issue by sticknor** [jadsonlourenco/react-native-shake-event#3]
Hi! Thanks for this great and easy-to-use package. 
I'm excited about the new android support. 

I am trying to add a listener for the beginning of a shake event, rather than the end.
I have changed this myself for my project. But wondering if it is an option you might include?

**Comment by jadsonlourenco** [comment]
Well, I'm not using RN for few time, but if you can submit a PR with that will be great.

**Comment by jadsonlourenco** [comment]
I think @sticknor is right, we can have all states of the "motion": **didBegan**, **cancelled** and **didEnd**, so the event name to observer on JS side can be like "shakeBegan", "shakeCancelled" and "shakeEnd".

**Comment by AntoineGrandchamp** [comment]
I would like to implement the didBegan motion, but I am not familiar with Objective C. Could you explain me where I need to add them ?

**Comment by jadsonlourenco** [comment]
@sticknor did it https://github.com/CMP-Studio/react-native-shake-event/commit/4b9ac8ef146d33adebb4be0540b67f7d3bd1497e but not send a PR

**Comment by jadsonlourenco** [comment]
Unfortunately I have not used React Native for a long time, over a year, so I can not support and maintain this module. So I'll close all issues. Sorry to all.
