### ISSUE TITLE
support RN 0.40.0

### ISSUE THREAD

**Issue by gre** [jadsonlourenco/react-native-shake-event#4]
( needs to fix these breaking changes https://github.com/facebook/react-native/releases/tag/v0.40.0 )

**Comment by jadsonlourenco** [comment]
:heart_eyes: No way, my honor have you @gre here, your packages help me a lot and many of people of React world.

Ping @richardgill can you help with this? Thank you! :+1:

**Comment by gre** [comment]
I can provide a PR if i have a bit more time later :)

**Comment by kthelgason** [comment]
Seems @bjornorri has fixed this in #5
