### ISSUE TITLE
Doesn't work on Android (RN 0.45)

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [jadsonlourenco/react-native-shake-event#9]
Thank you for creating this useful library.

However, when I updated my project to React Native 0.45, it doesn't work anymore on Android. On IOS it still works fine.

**Comment by jadsonlourenco** [comment]
Unfortunately I have not used React Native for a long time, over a year, so I can not support and maintain this module. So I'll close all issues. Sorry to all.

**Comment by brunolemos** [comment]
Maybe you should leave the issues opened. 

I checked this lib, noticed all issues were closed, thought "Nice, seems to work well", implemented, but now I noticed it doesn't work on Android :(

**Comment by negativetwelve** [comment]
Hi @brunolemos - if it's for a new version of react-native, please open a new issue. That way we can track the exact problem and make sure that it gets fixed

**Comment by brunolemos** [comment]
@negativetwelve sorry, it seems it does work. I just had a hard time making the shake gesture in the emulator.

**Comment by negativetwelve** [comment]
no problem, thanks for letting us know!
